name: Build & Release Tor XCFramework with dSYMs

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true
      release_branch:
        description: 'Branch to push XCFramework to'
        required: true
        default: 'main'
      xcode_version:
        description: 'Xcode version (e.g. 15.2)'
        required: false
        default: ''

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: macos-latest
    env:
      FRAMEWORK_NAME: Tor
      XCFRAMEWORK_OUT: Tor.xcframework
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Optionally select Xcode
        if: ${{ inputs.xcode_version != '' }}
        run: |
          sudo xcode-select -s /Applications/Xcode-${{ inputs.xcode_version }}.app || true
          echo "Using Xcode: $(xcodebuild -version)"
        shell: bash

      - name: Prepare XCFramework artifact
        run: |
          set -euo pipefail
          SRC_XC="Sources/SwiftTor/Tor.xcframework"
          if [ ! -d "$SRC_XC" ]; then
            echo "Expected XCFramework not found at $SRC_XC"
            ls -la "Sources/SwiftTor" || true
            exit 1
          fi
          echo "Found XCFramework at: $SRC_XC"
          # Repack as a zip to keep folder structure intact in release asset
          rm -f Tor.xcframework.zip
          /usr/bin/ditto -ck --sequesterRsrc --keepParent "$SRC_XC" "Tor.xcframework.zip"
          echo "Created artifact: Tor.xcframework.zip"
        shell: bash

      - name: Optionally commit XCFramework to branch
        if: ${{ inputs.release_branch != '' }}
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: actions@github.com
        run: |
          set -e
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          # Ensure we're on the target branch
          git checkout -b "${{ inputs.release_branch }}" || git checkout "${{ inputs.release_branch }}"
          # Sync the XCFramework in repo root for convenience (optional)
          rm -rf "./Tor.xcframework" || true
          cp -R "Sources/SwiftTor/Tor.xcframework" "./Tor.xcframework"
          git add ./Tor.xcframework
          git commit -m "Sync Tor.xcframework for release ${{ inputs.release_tag }}" || echo "no changes to commit"
          git push origin HEAD:${{ inputs.release_branch }}
        shell: bash

      - name: Create GitHub release and upload artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag }}
          name: ${{ inputs.release_tag }}
          body: "XCFramework artifact (prebuilt) with dSYMs, packaged from repository."
          files: |
            Tor.xcframework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}